
services:
  api:
    image: api:latest
    container_name: api
    volumes:
      - ${PWD}/api:/app/api
      - ${PWD}/json_schemas:/json_schemas
    build: .
    ports:
    - "8000:8000"
    depends_on:
    - db
    - broker
    env_file:
    - .env
  consumer:
    image: consumer:latest
    container_name: consumer
    volumes:
      - ${PWD}/workers/js/index.js:/app/index.js
    build:
      context: ./workers/js
      dockerfile: Dockerfile
    depends_on:
      - db
      - broker
    env_file:
      - .env
  db:
    image: postgres:17
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"

  broker:
    image: rabbitmq:management
    container_name: rabbitmq
    volumes:
      - broker-lib:/var/lib/rabbitmq
      - broker-log:/var/log/rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 8080:8080
    environment:
      RABBITMQ_DEFAULT_USER: kalo
      RABBITMQ_DEFAULT_PASS: kalo

volumes:
  db-data:
    driver: local
  broker-lib:
    driver: local
  broker-log:
    driver: local