FROM python:3.11-slim
WORKDIR /app
COPY --from=ghcr.io/astral-sh/uv:latest uv /usr/local/bin/uv
# No optim... just for local devs.
RUN apt-get update -y
RUN apt-get install -y npm
RUN npm install -g nodemon
 
COPY pyproject.toml .
RUN uv sync
COPY api api
COPY listener listener
COPY scripts/entrypoint_dev.sh /app/entrypoint.sh
ENV PATH=/app/.venv/bin/:$PATH
CMD ["./entrypoint.sh"]