FROM python:3.11-slim
WORKDIR /app
COPY --from=ghcr.io/astral-sh/uv:latest uv /usr/local/bin/uv
# No optim... just for local devs.
RUN apt-get update -y
RUN apt-get install -y npm postgresql-client
RUN npm install -g nodemon

# Install dependencies
COPY pyproject.toml .
RUN uv sync

# Copying the application code
COPY api api
COPY listener listener
COPY migrations migrations
COPY alembic.ini .
COPY scripts/entrypoint_dev.sh /app/entrypoint.sh

ENV PATH=/app/.venv/bin/:$PATH
ENV PYTHONPATH=/app
CMD ["./entrypoint.sh"]