{{- range $worker := .Values.workers }}
{{- if and $worker.enabled $worker.extraSecret }}
{{- range $secret := $worker.extraSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" $) $secret.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helper.labels" (dict "root" $ "componentName" "worker") | nindent 4 }}
    worker.name: {{ $worker.name }}
    async-api.io/resource-type: secret
type: Opaque
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
