{{ if .Capabilities.APIVersions.Has "keda.sh/v1alpha1" -}}
{{- range .Values.workers }}
{{- if and .enabled (and .kedaAutoscaler .kedaAutoscaler.enabled) }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ printf "%s-worker-%s-rabbitmq-auth" (include "helper.fullname" $) .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "helper.labels" (dict "root" $ "componentName" "worker") | nindent 4 }}
    worker.name: {{ .name }}
    async-api.io/resource-type: trigger-authentication
spec:
  configMapTargetRef:
  - parameter: username
    name: {{ include "helper.fullname" $ }}-env-config
    key: BROKER_USERNAME
  secretTargetRef:
  - parameter: password
    name: {{ include "chart.brokerPasswordSecretName" $ }}
    key: {{ include "chart.brokerPasswordSecretKey" $ }}
{{- end }}
{{- end }}
{{- end }}
