{{/*
Broker secret creation based on priority:
1. urlFromSecret -> no secret creation, use existing BROKER_URL
2. url -> create secret with BROKER_URL
3. components -> create secret with BROKER_HOST, BROKER_PORT, etc.
4. rabbitmq dependency with components -> create secret with BROKER_HOST, BROKER_PASSWORD, etc.
5. rabbitmq dependency without password -> use rabbitmq generated secret for BROKER_PASSWORD
*/}}

{{- if not .Values.broker.urlFromSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-broker" (include "helper.fullname" .) }}
  labels:
    {{- include "helper.labels" (dict "root" . "componentName" "api") | nindent 4 }}
    app.kubernetes.io/component: broker
    async-api.io/type: configuration
type: Opaque
data:
  {{- if .Values.broker.url }}
  {{/* Priority 2: url provided */}}
  BROKER_URL: {{ .Values.broker.url | b64enc | quote }}
  {{- else if or .Values.broker.components.host .Values.broker.components.username .Values.broker.components.password }}
  {{/* Priority 3: components provided */}}
  BROKER_HOST: {{ .Values.broker.components.host | b64enc | quote }}
  BROKER_PORT: {{ (.Values.broker.components.port | toString) | b64enc | quote }}
  BROKER_USERNAME: {{ .Values.broker.components.username | b64enc | quote }}
  BROKER_VHOST: {{ .Values.broker.components.vhost | b64enc | quote }}
  BROKER_SCHEME: {{ .Values.broker.components.scheme | b64enc | quote }}
  {{- if .Values.broker.components.password }}
  BROKER_PASSWORD: {{ .Values.broker.components.password | b64enc | quote }}
  {{- end }}
  {{- else if .Values.rabbitmq.enabled }}
  {{/* Priority 4 & 5: rabbitmq dependency */}}
  BROKER_HOST: {{ (include "chart.rabbitmq.fullname" .) | b64enc | quote }}
  BROKER_PORT: {{ (.Values.rabbitmq.service.ports.amqp | toString) | b64enc | quote }}
  BROKER_USERNAME: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  BROKER_VHOST: {{ .Values.broker.components.vhost | b64enc | quote }}
  BROKER_SCHEME: {{ .Values.broker.components.scheme | b64enc | quote }}
  {{- if .Values.rabbitmq.auth.password }}
  BROKER_PASSWORD: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
