{{/*
Database secret creation based on priority:
1. urlFromSecret -> no secret creation, use existing DATABASE_URL
2. url -> create secret with DATABASE_URL
3. components -> create secret with DB_HOST, DB_PORT, etc.
4. postgresql dependency with components -> create secret with DB_HOST, DB_PASSWORD, etc.
5. postgresql dependency without password -> use postgresql generated secret for DB_PASSWORD
*/}}

{{- if not .Values.database.urlFromSecret.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-database" (include "helper.fullname" .) }}
  labels:
    {{- include "helper.labels" (dict "root" . "componentName" "api") | nindent 4 }}
    app.kubernetes.io/component: database
    async-api.io/type: configuration
type: Opaque
data:
  {{- if .Values.database.url }}
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
  {{- else if and .Values.database.components.host .Values.database.components.name .Values.database.components.username .Values.database.components.password }}
  DB_HOST: {{ .Values.database.components.host | b64enc | quote }}
  DB_PORT: {{ (.Values.database.components.port | toString) | b64enc | quote }}
  DB_NAME: {{ .Values.database.components.name | b64enc | quote }}
  DB_USERNAME: {{ .Values.database.components.username | b64enc | quote }}
  DB_SCHEME: {{ .Values.database.components.scheme | b64enc | quote }}
  {{- if .Values.database.components.password }}
  DB_PASSWORD: {{ .Values.database.components.password | b64enc | quote }}
  {{- end }}
  {{- else if .Values.postgresql.enabled }}
  DB_HOST: {{ (include "chart.postgresql.fullname" .) | b64enc | quote }}
  DB_PORT: {{ (.Values.postgresql.primary.service.ports.postgresql | toString) | b64enc | quote }}
  DB_NAME: {{ .Values.postgresql.auth.database | b64enc | quote }}
  DB_USERNAME: {{ .Values.postgresql.auth.username | b64enc | quote }}
  DB_SCHEME: {{ .Values.database.components.scheme | b64enc | quote }}
  {{- if .Values.postgresql.auth.password }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
