{{- if or (include "chart.databaseUrl" .) (include "chart.brokerUrl" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-%s" (include "helper.fullname" .) "api" "connection" }}
  labels:
    {{- include "helper.labels" (dict "root" . "componentName" "api") | nindent 4 }}
    app.kubernetes.io/component: connection
    async-api.io/type: configuration
  {{- with .Values.api.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if include "chart.databaseUrl" . }}
  # Individual database parameters (cleaner approach)
  DB_HOST: {{ include "chart.databaseHost" . | b64enc | quote }}
  DB_PORT: {{ include "chart.databasePort" . | toString | b64enc | quote }}
  DB_USER: {{ include "chart.databaseUser" . | b64enc | quote }}
  DB_PASSWORD: {{ include "chart.databasePassword" . | b64enc | quote }}
  DB_NAME: {{ include "chart.databaseName" . | b64enc | quote }}
  # Legacy DATABASE_URL for backward compatibility
  DATABASE_URL: {{ include "chart.databaseUrl" . | b64enc | quote }}
  {{- end }}
  {{- if include "chart.brokerUrl" . }}
  BROKER_URL: {{ include "chart.brokerUrl" . | b64enc | quote }}
  {{- end }}
{{- end -}}
