{{- if or (.Values.database.password) (.Values.postgresql.enabled) (.Values.broker.password) (.Values.rabbitmq.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helper.fullname" . }}-passwords
  labels:
    {{- include "helper.labels" (dict "root" . "componentName" "api") | nindent 4 }}
    app.kubernetes.io/component: passwords
    async-api.io/type: configuration
type: Opaque
data:
  {{- if or (.Values.database.password) (.Values.postgresql.enabled) }}
  db-password: {{ include "chart.databasePassword" . | b64enc | quote }}
  {{- end }}
  {{- if or (.Values.broker.password) (.Values.rabbitmq.enabled) }}
  broker-password: {{ include "chart.brokerPassword" . | b64enc | quote }}
  {{- end }}
{{- end }}
