- name: client1
  client_id: ZERJGbnkzjhejuyiyaze
  client_secret: $CLIENT_SECRET_1
  authorizations:
    # - service: all # all access
    #   quotas: 100 Quotas for each services
    - service: example1
      quotas: 100 
    - service: example2
      # quotas: 100 # Default: No quotas
