{{- if .Values.api.listener.env -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "listener" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "api")) | nindent 4 }}
data:
  {{- include "helper.env" .Values.api.listener | indent 2 }}
{{- end -}}
