{{- if or .Values.worker.secrets .Values.global.secrets -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "worker" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "worker")) | nindent 4 }}
data:
  {{- if .Values.global.secrets -}}
  {{- include "helper.secret" .Values.global | indent 2 }}
  {{- end -}}
  {{- if .Values.worker.secrets -}}
  {{- include "helper.secret" .Values.worker | indent 2 }}
  {{- end -}}
{{- end -}}
