{{- if and .Values.worker.serviceAccount.enabled .Values.worker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.worker.serviceAccount.name | default (printf "%s-%s" (include "helper.fullname" .) "worker") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "worker")) | nindent 4 }}
  {{- if .Values.worker.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml .Values.worker.serviceAccount.annotations) . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.worker.serviceAccount.automountServiceAccountToken }}
{{- end }}
